[workspace]
members = [
    "crates/clash-config",
    "crates/common",
    "crates/diag",
    "crates/id_alloc",
    "crates/nsproxy-core",
    "crates/nsproxy-ui",
    "crates/term-view",
]
exclude = [
    "crates/clone3",
    "crates/hickory-dns",
    "crates/ipstack",
    "crates/netlink-packet-audit",
    "crates/netlink-packet-core",
    "crates/netlink-packet-route",
    "crates/netlink-packet-utils",
    "crates/netlink-proto",
    "crates/netlink-sys",
    "crates/pidfd",
    "crates/rtnetlink",
    "crates/rust-tun",
    "crates/rustables",
    "crates/socks5-impl",
    "crates/trojan-proto",
    "crates/tun2socks5",
    "crates/tun_bench",
    "crates/warp",
]
resolver = "3"

[profile.dev.package.term-view]
opt-level = 3

[profile.dev.package.egui]
opt-level = 3

[profile.dev.package.eframe]
opt-level = 3

[profile.dev.package.epaint]
opt-level = 3

[profile.dev.package.egui_extras]
opt-level = 3

[profile.dev.package.egui_plot]
opt-level = 3

[profile.dev.package.egui_code_editor]
opt-level = 3

[profile.dev.package.egui-phosphor]
opt-level = 3

[profile.dev.package.egui_json_tree]
opt-level = 3

[profile.dev.package.egui_sgr]
opt-level = 3

[workspace.package]
version = "0.3.5"
edition = "2021"
license = "MIT"
repository = "https://github.com/ple1n/nsproxy"
[profile.dev]
panic = "abort"
opt-level = 0       # No optimizations → fastest compile
debug = true        # Keep debug symbols
incremental = true  # Enable incremental builds
codegen-units = 16  
lto = false         # No link-time optimization

[profile.release]
strip = false
opt-level = 3
lto = true
debug = true
# Just strip manually


[patch.crates-io]
nsproxy-hickory-proto = { path = "../hickory-dns/crates/proto" }
nsproxy-hickory-client = { path = "../hickory-dns/crates/client" }
nsproxy-hickory-resolver = { path = "../hickory-dns/crates/resolver" }
nsproxy-hickory-recursor = { path = "../hickory-dns/crates/recursor" }
nsproxy-hickory-server = { path = "../hickory-dns/crates/server" }
nsproxy-hickory-dns = { path = "../hickory-dns/bin" }
nsproxy-hickory-util = { path = "../hickory-dns/util" }

[workspace.dependencies]
tun-rs = { version = "2.7.2", features = ["async_io"] }
flume = "0.11.1"
rust-tun = { package = "nsproxy-tun", version = "0.6.1", path = "crates/rust-tun" }
netlink-ops = { path = "crates/netlink-ops" }
rtnetlink = { package = "nsproxy-rtnetlink", version = "0.18.1", path = "crates/rtnetlink" }
rustables = { package = "nsproxy-rustables", version = "0.8.1", path = "crates/rustables" }
netlink-packet-audit = { package = "nsproxy-netlink-packet-audit", version = "0.6.1", path = "crates/netlink-packet-audit" }
netlink-sys = { package = "nsproxy-netlink-sys", version = "0.8.5", path = "crates/netlink-sys" }
netlink-proto = { package = "nsproxy-netlink-proto", version = "0.12.0", path = "crates/netlink-proto" }
tun2socks5 = { package = "nsproxy-tun2socks5", version = "0.1.0", path = "crates/tun2socks5" }
socks5-impl = { package = "nsproxy-socks5-impl", version = "0.5.6", path = "crates/socks5-impl" }
pidfd = { package = "nsproxy-pidfd", version = "0.2.4", path = "crates/pidfd" }
ipstack = { package = "nsproxy-ipstack", version = "0.0.2", path = "crates/ipstack" }
clone3 = { package = "nsproxy-clone3", version = "0.2.3", path = "crates/clone3" }
nsproxy-ui = { path = "crates/nsproxy-ui" }
netlink-packet-route = { package = "nsproxy-netlink-packet-route", version = "0.25.1", path = "crates/netlink-packet-route" }
netlink-packet-utils = { package = "nsproxy-netlink-packet-utils", version = "0.6.0", path = "crates/netlink-packet-utils" }
netlink-packet-core = { package = "nsproxy-netlink-packet-core", version = "0.8.0", path = "crates/netlink-packet-core" }
fs4 = { version = "0.13", features = ["tokio"] }
rlimit = "0.10.1"
passfd = { version = "*" }
which = "8.0.0"
chrono = "0.4"

# daemonize-me = "2.0.1"
